version: "3"

services:
  mam_updater:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CRON_SCHEDULE=0 */2 * * *
    volumes:
      - ./data:/data
    restart: unless-stopped
